= Android

Adventures in Android development. This directory is dedicated to exploration of android app development.
The `fiddle.sh` script can be used to extend or test drive this collection. The following table outlines how.

=== fiddle.sh Android Commands

[cols="2,2,5a"]
|===
|Create
|`fiddle "create" "android" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Emulate
|`fiddle "emulate" "android"`
|link:emulate.md[sample output & additional details]
|Fork
|`fiddle "fork" "android" "0000" "fiddle-0003-TemplateFork"`
|link:fork.md[sample output & additional details]
|Delete
|`fiddle "delete" "android" "0000"`
|link:delete.md[sample output & additional details]
|Refactor
|`fiddle "refactor" "android" "0000" "fiddle-0100-EmptyTemplate"`
|link:refactor.md[sample output & additional details]
|Start
|`fiddle "start" "android" "0000"`
|link:start.md[sample output & additional details]
|List
|`fiddle "list" "android"`
|link:list.md[sample output & additional details]
|===


== Android Studio Setup (Mac OS X)

In order to build native Android apps, the best IDE is Android Studio. In addition, it provides easy access to the GUI
versions of Android SDK and AVD Managers. The Studio bundle for Mac OS X can be downloaded from
link:https://developer.android.com/studio/[developer.android.com/studio].


== Android Commandline Setup (Mac OS X)

In order to run android based fiddles, android commandline tools need to be setup. To complete this setup run
`fiddle setup mac android` or complete the following steps manually.


1.  Install Homebrew:

    `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

2.  Install Java8:

    `brew tap caskroom/versions`
    `brew cask install java8`

3.  Set the JAVA_HOME system environment variable in your .zshrc (and/or) .bash_profile files:

    `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`

4.  Install the Android SDK

    `brew cask install android-sdk`

5.  Set the ANDROID_HOME system environment variable in your .zshrc (and/or) .bash_profile files:

    `export ANDROID_HOME=/usr/local/share/android-sdk`

6.  install all packages for the Android SDK Platform 28, Android SDK Build-Tools 28.0.3 or later, Android Support
    Repository, Google Repository and any other SDKs that you may need:

    `$ANDROID_HOME/tools/bin/sdkmanager "tools" "emulator" "platform-tools" "platforms;android-28" "build-tools;28.0.3"
    "extras;android;m2repository" "extras;google;m2repository"`

7.  Launch Android Studio and open `Android Virtual Device (AVD) Manager`, create an Android Virtual Device, called `fiddler`

8.  To test your configuration, use the link:start.md[fiddle.sh start ...] command


== Online Resources
*   link:https://developer.android.com/index.html[Android API libraries and developer tools]
*   link:http://www.androidcentral.com/android-201-10-basic-terminal-commands-you-should-know[Ten basic Android terminal commands you should know]
*   link:http://stackoverflow.com/questions/20801042/how-to-create-android-project-with-gradle-from-command-line[How to create android project with gradle from command line?]
*   link:http://tools.android.com/tech-docs/new-build-system/version-compatibility[Android Gradle Plugin Gradle Version Requirements]
